### ISSUE TITLE
can not run with 1K sequences (memory issues)

### ISSUE THREAD

**Issue by jcdelpiano** [ranganathanlab/bmDCA#3]
Dear all, 

I have been trying to use bmdca from a multiple sequence alignment file, with 996 Prot sequences. The thing is bmdca is using the whole available memory (60gb, plus swp memory). Is this normal? after a while, the run is automatically killed.

Is there something that I'm doing wrong? anything that I could do to optimize this?

Many thanks for your help and time!

Best, 

J.

**Comment by sudorook** [comment]
How many positions are in the alignment?

**Comment by jcdelpiano** [comment]
around 900 positions

**Comment by sudorook** [comment]
That's strange. I didn't think 900 positions would require more than 20 Gb memory. Not sure why it's taking more than 60 Gb.

What is the terminal output when it crashes? It would help to paste the contents of the `bmdca_params.conf` that gets generated at runtime file here as well.

**Comment by jcdelpiano** [comment]
My mistake, it wasn't 900 alignment positions, but rather 900 residues the biggest protein in the alignment. Probably, it was more than 900.

Now, I manage to start one run that has 1000 alignment positions, and it is using 42Gb of memory. Does this sounds correct? here are the parameters. Is there any estimate for the time it will take a run of this size?

[bmDCA]
lambda_reg1=0.01
lambda_reg2=0.01
step_max=2000
error_max=1e-05
save_parameters=20
save_best_steps=32559
random_seed=1
use_reparametrization=1
epsilon_0_h=0.01
epsilon_0_J=0.001
adapt_up=1.5
adapt_down=0.6
min_step_h=0.001
max_step_h=2.5
min_step_J=1e-05
max_step_J_N=2.5
error_min_update=-1
t_wait_0=10000
delta_t_0=100
check_ergo=1
adapt_up_time=1.5
adapt_down_time=0.6
step_importance_max=1
coherence_min=0.9999
M=1000
count_max=10
init_sample=0
init_sample_file=
sampler=mh
output_binary=1

**Comment by sudorook** [comment]
That's still seems high... How are you reading memory usage? `top`?

There is a [memory profiler](https://pypi.org/project/memory-profiler/) that generates a time series of memory use that can help pinpoint what step is causing the usage to get that high. It's simple to use: first, `mprof run bmdca ...` and then plot the output `mprof plot ...`.

Memory usage scales roughly quadratically with the number of positions in the alignment. bmDCA stores several data structures of N * (N-1) / 2 * Q * Q + N * Q values (N=# positions, Q=# amino acids) in memory. MSA size affects usage, too, but not as much, as it's just M * N * Q values (M=# sequences).

If possible, one could preprocess the MSA (e.g., removing highly gapped positions) to shrink the alignment a bit. There is a script called `scaProcessMSA` in the pySCA repository that does this. Shrinking the alignment will reduce memory usage, though it adds the headache of mapping the processed sequences back to the original ones.

If memory use remains an issue, I suppose an easy way to halve it would be to use floats instead of doubles. (In the src/ directory, run `find . -type f -exec sed -i "s/double/float/g" {} +` and then re-compile and re-install.) I haven't checked whether the loss of precision matters, but I doubt it does.

**Comment by jcdelpiano** [comment]
Thank you for all the suggestions. I will try to do everything stated before, but I don't want to kill a run that is still running. Do you have an estimate for the time it will take a run with an alignment size of 1000? Thanks again.

**Comment by sudorook** [comment]
It will take a long time. For 1000 positions, I'd say at least several days with default settings. The program is not quick.

Some considerations:

1. During runtime, look into the bmdca_run.log file. In it, there is a field called `error_tot` which is the rms error of the sequences sampled from the learned model at a given iteration versus the original multiple sequence alignment. The value should be decreasing steadily.

2. An additional consideration, especially for the larger proteins, is whether the sequences in the MSA are clustered. For example, if you project the MSA onto principal components of the sequence similarity matrix, are there distinct clusters? If there are, then be wary of the MCMC approach used to sample parameters at each step in the inference loop. Trajectories risk getting stuck in optima. In that case, increase `count_max` and decrease `M` correspondingly in the config file. One way to check this manually is to project the sampled sequences (MC_samples_[iteration].txt) onto the MSA components and compare with the original MSA projection.

3. The default error threshold for termination of 1e-5 is far, far too low to be reached in a reasonable amount of time. For 10k samples, a threshold of 0.003 to 0.004 is more reasonable.

Regarding the original question, let me know if you get anywhere with diagnosing memory use. Short of that, you can upload the MSA, and I'll take a look at it whenever I get the chance.

**Comment by jcdelpiano** [comment]
Thank you so much for all the information. I'm attaching the alignment file for you. I will follow you suggestions. Thank you again for all the help.

[amyThermo.txt](https://github.com/ranganathanlab/bmDCA/files/5059323/amyThermo.txt)

**Comment by jcdelpiano** [comment]
just to keep you updated on this, by using floats instead of doubles I managed to lower the memory usage from 42gb to 16gb, which is great. Thanks for all the help!

**Comment by sudorook** [comment]
I took a look at that alignment. There are almost 9000 positions in it, so it is no surprise that it used up all your RAM. Something like this will need to be pre-processed or re-computed. One reason is the memory issue, but a more important one is that almost all the positions are gaps. It is of little value to have bmDCA attempt to train a model that produces sequences that are mostly gaps.
